# Generated by Django 5.0.7 on 2024-07-25 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('demoUrl', models.CharField(blank=True, null=True)),
                ('viewUrl', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
