# Generated by Django 5.0.7 on 2024-07-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githabURL',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='imgUrl',
            field=models.CharField(blank=True, null=True),
        ),
    ]
