# Generated by Django 5.0.7 on 2024-07-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_githaburl_project_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
