# Generated by Django 5.0.7 on 2024-07-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('photoPerfilUrl', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('photoPortadaUrl', models.CharField(blank=True, null=True)),
                ('cell', models.CharField(blank=True, max_length=255, null=True)),
                ('titleAboutMy', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptionAboutMy', models.CharField(blank=True, null=True)),
                ('shortDescriptionAboutMy', models.CharField(blank=True, null=True)),
                ('descriptionSkills', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
